### ISSUE TITLE
Shell Context Menu Handler Simple doesn't work in Win7 64b

### ISSUE THREAD

**Issue by radioactivebean** [landrix/The-new-Drag-and-Drop-Component-Suite-for-Delphi#12]
Hi, I have an issue, maybe you can point me in the right direction.
I'm using XE7 on Windows7 64b

1. I build the project using target platform Win32, no errors and the DLL is created OK
2. I register the DLL using: regsvr32.exe c:\path_of_dll\SimpleContextMenuHandlerShellExt.dll
3. I get a window from regsvr32 with the message "Success"
4. The CLSID used in the project appears in the RegistryEditor with the neccesary subkeys
5. When I right-click on a file in the Explorer nothing happens
6. I unregister the DLL using: regsvr32.exe /u c:\path_of_dll\SimpleContextMenuHandlerShellExt.dll

7. I compile the project using target platform Win64 and get the following error:
[dcc64 Fatal Error] ContextMenuHandlerMain.pas(6): F2048 Bad unit format: 'DragDrop.dcu' - Expected version: 28.0, Windows Unicode(x64) Found version: 28.0, Windows Unicode(x86)

What I'm doing wrong? Is the target platform the problem?

Thanks in advance...

**Comment by landrix** [comment]
I think you have the same output path for Win32 and Win64. Please Re-Compile the hole project for Win64.
