### ISSUE TITLE
Compiling under XE8 - DragDropFormats.pas

### ISSUE THREAD

**Issue by mmckenziekapiti** [landrix/The-new-Drag-and-Drop-Component-Suite-for-Delphi#13]
Compiling DragDropFormats.pas with XE8 fails with the error:

[dcc32 Error] DragDropFormats.pas(133): E2037 Declaration of 'Stat' differs from previous declaration
[dcc32 Error] DragDropFormats.pas(135): E2037 Declaration of 'Seek' differs from previous declaration
[dcc32 Error] DragDropFormats.pas(137): E2037 Declaration of 'Read' differs from previous decl
[dcc32 Error] DragDropFormats.pas(139): E2037 Declaration of 'CopyTo' differs from previous decl
= = = =

In DragDropFormats.pas->
function TFixedStreamAdapter.Stat(out statstg: TStatStg; grfStatFlag: Integer): HResult;

in System.Classes -->
function TStreamAdapter.Stat(out statstg: TStatStg; grfStatFlag: DWORD): HResult;

**Comment by landrix** [comment]
Thanks, i will check this.

**Comment by landrix** [comment]
Fixed

**Comment by mmckenziekapiti** [comment]
Thank you. My application lives again in XE8!
