### ISSUE TITLE
Office2013 ...

### ISSUE THREAD

**Issue by dspenardicc** [landrix/The-new-Drag-and-Drop-Component-Suite-for-Delphi#9]
Works well until office 2010 ... With 2013, it says 'Either there is no default mail client or the current mail client cannot fulfill the messaging request

Is there a fix ?

**Comment by landrix** [comment]
Where is the context with the drag drop component? What do you want to do?

**Comment by dspenardicc** [comment]
I tried the Demo supplied for Drap and Drop operations with Outlook (OutlookDemo.dpr) with Delphi XE5 and XE7 using 
1) Windows 8 with Outlook2013 and
2) Windows 7 with Outlook2013

I also tried those combinations with Outlook2010 and it works fine.

**Comment by landrix** [comment]
I have no Outlook2013. If I have time, I look after a trial version.

**Comment by landrix** [comment]
I have installed Outlook2013 Trial and there is no problem with drag and drop one or more messages for me.
Have you tested with several emails?

**Comment by dspenardicc** [comment]
The demo raises the exception as soon as i start the application.  I don't even have the time to try the drag and drop operation.

There may be another possibility : My Outlook2013 is 64 bits vs 32bits for the delphi app demo ... could it be the source of the problem ?

I'll change my 64 bit Outlook for a 32 bit version and then retry.

**Comment by landrix** [comment]
This could be possible. I have installed Office2013 in a 32 bit VM.

**Comment by landrix** [comment]
Yes, with no Office on my maschine, both failes, 32 and 64 bit. The reason is the wrong Office Version

**Comment by dspenardicc** [comment]
Test done : works fine with office2013 32bits ...

Thank's for your support.

P.S. We will eventually work on a 64 bit version of our app and the Drag&Drop component.

**Comment by landrix** [comment]
Thanks, I am grateful for any help.
